### ISSUE TITLE
Returned value for SpamassRules

### ISSUE THREAD

**Issue by maxstralin** [mailjet/mailjet-apiv3-dotnet#32] opened 2019-03-17 10:15 UTC
Hi.

[The documentation](https://dev.mailjet.com/reference/email/messages/#v3_get_message) doesn't state how the string is formatted for `https://api.mailjet.com/v3/REST/message/`.`SpamassRules`.

The example for a single message seems to return an object (`{}`) but the documentation says string, while the example for multiple messages seems to return an empty string (`""`).
Can't see what type of value that string might have, e.g. "Rule1;Rule2", "Rule1 Rule2", "Rule1,Rule2".

**Comment by kmanchikov** [comment] 2019-08-16 14:02
Hi, 

Thank you for pointing that one out and indeed our Reference currently doesn't have an example as to what to expect when it comes to `Spamassasin` rules or scores. 

This issue has been reported internally and is currently awaiting for a fix. Once I grab my hands to more information in regards to that one I will be happy to let you know.

**Comment by goacoustic** [comment] 2021-02-02 10:28
Hi,
seems that the issue is outdated, going to close it.

**Closed by goacoustic** 2021-02-02 10:28 UTC
