### ISSUE TITLE
Linux with .net core 3.0 + OpenSSL 1.1.1 doesn't work

### ISSUE THREAD

**Issue by zalza13** [mailjet/mailjet-apiv3-dotnet#41] opened 2019-11-26 21:14 UTC
Hi! In Ubuntu 18.04 with OpenSSL 1.1.1 and .net core 3.0 the client doesn't work. The error is: **The SSL connection could not be established, see inner exception.**

The problem is .net core 3.0 only. 

this code skips the certificate validation

```
private void InitHttpClient(HttpMessageHandler httpMessageHandler)
        {
            var handler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
                {
                    if (errors == SslPolicyErrors.None)
                        return true;
                    else
                    {
                        Console.WriteLine("MailJet sslPolicyErrors {0}", errors);
                    }

                    return true;
                }
            };

            // Create HttpClient
            //_httpClient = (httpMessageHandler != null) ? new HttpClient(httpMessageHandler) : new HttpClient();
            _httpClient = new HttpClient(handler)
```

Thanks!

**Comment by Tratcher** [comment] 2019-12-06 22:03
> see inner exception.

What was the inner exception?

**Comment by Tratcher** [comment] 2019-12-06 22:04
This probably needs to be moved to https://github.com/dotnet/runtime.

**Comment by programando-ideas** [comment] 2019-12-06 22:22
Hi @Tratcher! thanks for your attention. I clarify, this happens on Ubuntu 18.04 with OpenSSL 1.1.1 and dotnet core 3.0.

This is the exception:

```
The SSL connection could not be established, see inner exception.

InnerException.Message: The remote certificate is invalid according to the validation procedure.

at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)   
at System.Net.Http.HttpConnection
```

**Comment by Tratcher** [comment] 2019-12-06 22:35
Does this repro if you call HttpClient directly? Or is additional configuration needed?
```
            var client = new HttpClient();
            var result = client.GetAsync("https://api.twilio.com:8443/").Result;
            Console.WriteLine(result);
```

**Comment by programando-ideas** [comment] 2019-12-06 23:36
This is the code of my application

```
MailjetClient client = new MailjetClient(_apiKey, _apiSecret)
            {
                Version = ApiVersion.V3_1,
            };

            JObject objEmail = new JObject {
                        {"From", new JObject {
                            {"Email", mensaje.IdOrigenNavigation.DireccionOrigen},
                            {"Name", mensaje.IdOrigenNavigation.NombreOrigen}
                        }},
                        {"To", new JArray {
                          new JObject {
                           {"Email", mensaje.Destinatario},
                           {"Name", mensaje.DestinatarioNombre}
                           }
                        }},
                        {"Subject", mensaje.DatosAdicionales.Asunto},
                        {"TextPart", mensaje.DatosAdicionales.MensajeFormatoTexto},
                        {"HTMLPart", mensaje.DatosAdicionales.MensajeFormatoHTML}
                 };

            if (mensaje.DatosAdicionales.ArchivoAdjunto != null)
                objEmail.Add(
                    "Attachments", new JArray {
                      new JObject {
                       {"ContentType", mensaje.DatosAdicionales.ArchivoAdjunto.ContentType},
                       {"Filename", mensaje.DatosAdicionales.ArchivoAdjunto.Filename},
                       {"Base64Content", mensaje.DatosAdicionales.ArchivoAdjunto.DatosAdjuntosBASE64}}});

            MailjetRequest request = new MailjetRequest
            {
                Resource = Send.Resource,
            }.Property(Send.Messages, new JArray { objEmail });

            //Intenta enviar el mensaje
            MailjetResponse response;
            try
            {
                response = await client.PostAsync(request);
            }
            catch (Exception ex)
            {
                return new ResultadoProceso() { Respuesta = RESULTADO.ERROR, Ex = ex };
            }

            //Procesa la respuesta
            if (response.IsSuccessStatusCode)
            {
```

For now what I did was download the source code of the .net client, edit it and recompile it. I donwload from [here](https://github.com/mailjet/mailjet-apiv3-dotnet.git)

```
private void InitHttpClient(HttpMessageHandler httpMessageHandler)
        {
            var handler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
                {
                    if (errors == SslPolicyErrors.None)
                        return true;
                    else
                    {
                        Console.WriteLine("MailJet sslPolicyErrors {0}", errors);
                    }

                    return true;
                }
            };

            // Create HttpClient
            //_httpClient = (httpMessageHandler != null) ? new HttpClient(httpMessageHandler) : new HttpClient();
            _httpClient = new HttpClient(handler)
```

**Comment by Tratcher** [comment] 2019-12-06 23:42
Can you reproduce the issue without MailjetClient? Does calling HttpClient directly with MailJet or twilio urls fail for you?

**Comment by programando-ideas** [comment] 2019-12-06 23:55
With this code

```
            try
            {
                var client = new HttpClient();
                var result = client.GetAsync("https://api.twilio.com:8443/").Result;
                Console.WriteLine(result);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message, e);
            }
```

the error is

`One or more errors occurred. (The SSL connection could not be established, see inner exception.)`

**Comment by programando-ideas** [comment] 2019-12-07 00:08
Here more information about this problema

```
===================message==================
 Method: GET, RequestUri: 'https://api.twilio.com:8443/', Version: 1.1, Content: <null>, Headers: { }
==================cert==================
[Subject]  CN=*.twilio.com, O="Twilio, Inc.", L=San Francisco, S=California, C=US
[Issuer]  CN=Thawte RSA CA 2018, OU=www.digicert.com, O=DigiCert Inc, C=US
[Serial Number]  045E742DCB3F9400DC073EF3E6C3D3B1
[Not Before]  04/28/2019 19:00:00
[Not After]  04/28/2020 07:00:00
[Thumbprint]  068686C0A0ED02207A55CCF075BBCF24B1D9C049
==================chain==================
System.Security.Cryptography.X509Certificates.X509Chain
==================chain status==================
System.Security.Cryptography.X509Certificates.X509ChainStatus[]
==================errors==================
RemoteCertificateChainErrors
====================================================
Received certificate with subject CN=*.twilio.com, O="Twilio, Inc.", L=San Francisco, S=California, C=US
====================================================
Current policy errors: RemoteCertificateChainErrors
====================================================
status code = PartialChain
Status info = unable to get local issuer certificate
MailJet sslPolicyErrors RemoteCertificateChainErrors
ERROR: One or more errors occurred. (The SSL connection could not be established, see inner exception.)

```

**Comment by programando-ideas** [comment] 2019-12-07 00:09
Here more information

```
===================message==================
 Method: GET, RequestUri: 'https://api.twilio.com:8443/', Version: 1.1, Content: <null>, Headers: { }
==================cert==================
[Subject] CN=*.twilio.com, O="Twilio, Inc.", L=San Francisco, S=California, C=US
[Issuer] CN=Thawte RSA CA 2018, OU=www.digicert.com, O=DigiCert Inc, C=US
[Serial Number] 045E742DCB3F9400DC073EF3E6C3D3B1
[Not Before] 04/28/2019 19:00:00
[Not After] 04/28/2020 07:00:00
[Thumbprint] 068686C0A0ED02207A55CCF075BBCF24B1D9C049
==================chain==================
System.Security.Cryptography.X509Certificates.X509Chain
==================chain status==================
System.Security.Cryptography.X509Certificates.X509ChainStatus[]
==================errors==================
RemoteCertificateChainErrors
====================================================
Received certificate with subject CN=*.twilio.com, O="Twilio, Inc.", L=San Francisco, S=California, C=US
====================================================
Current policy errors: RemoteCertificateChainErrors
====================================================
status code = PartialChain
Status info = unable to get local issuer certificate
MailJet sslPolicyErrors RemoteCertificateChainErrors
ERROR: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
```

**Comment by programando-ideas** [comment] 2019-12-07 00:12
and more

```
$:/publicaciones/publish# openssl version
	OpenSSL 1.1.1d  10 Sep 2019

$:/publicaciones/publish# dotnet --list-runtimes
	Microsoft.AspNetCore.All 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
	Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
	Microsoft.AspNetCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
	Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
	Microsoft.AspNetCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
	Microsoft.NETCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
	Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
	Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

$:/publicaciones/publish# lsb_release -a
	No LSB modules are available.
	Distributor ID: Ubuntu
	Description:    Ubuntu 18.04.3 LTS
	Release:        18.04
	Codename:       bionic

```

**Comment by Tratcher** [comment] 2019-12-07 00:15
Ok, please open an issue at https://github.com/dotnet/runtime with these details. FYI my coworker was not able to reproduce this on a similar machine.

**Comment by programando-ideas** [comment] 2019-12-07 15:54
Thanks @Tratcher, already report the error to dotnet [https://github.com/dotnet/runtime/issues/662](https://github.com/dotnet/runtime/issues/662)

There is a similar problem [https://github.com/dotnet/core/issues/1941](https://github.com/dotnet/core/issues/1941) but, this solution did not  works for me :(

**Comment by programando-ideas** [comment] 2019-12-09 14:48
Hi @Tratcher, finally there is some problem with OpenSSL 1.1.1d on Linux. 

Please check [this](https://github.com/dotnet/runtime/issues/662#issuecomment-562899984)

Thanks!

**Comment by goacoustic** [comment] 2020-10-05 07:28
Hi guys, seems like the problem is not specific to MailJet SDK, but rather a specific OpenSSL version.
I'll close this for now.

**Closed by goacoustic** 2020-10-05 07:28 UTC
